/**
 * @file core type definitions for github apr bot
 * @path src/types.ts
 * 
 * interfaces for webhook processing, apr integration, and pull request creation. 
 * provides type safety for the entire workflow.
 * 
 * @core-features
 * - github webhook event types with data extraction
 * - apr result and patch structures for code modification
 * - repository and workflow identifiers for github api integration
 */

/**
 * simplified workflow event extracted from github webhook payload
 * contains only essential data needed for apr processing workflow
 */
export interface SimpleWorkflowEvent {
  installationId: number;        // github app installation id for auth
  repo: {                        // repository information for cloning and api calls
    owner: string;               // repository owner username
    name: string;                // repository name
  };
  workflowName: string;          // name of the failed workflow for filtering
  headSha: string;               // commit sha that triggered the workflow failure
  headBranch: string;            // branch that triggered the workflow for pr creation
  workflowUrl?: string;          // optional url to the failed workflow run for reference
}

/**
 * apr analysis result containing patches and execution status
 * simplified structure for mvp implementation
 */
export interface APRResult {
  success: boolean;              // whether apr analysis completed successfully
  patches: Patch[];              // array of generated code patches
  errorMessage?: string;         // descriptive error message if analysis failed
}

/**
 * individual patch generated by apr engine
 * contains essential information for applying automated code fixes
 */
export interface Patch {
  file: string;                  // file path relative to repository root
  line: number;                  // line number where patch should be applied (1-indexed)
  original: string;              // original code that should be replaced
  fixed: string;                 // fixed code to replace original content
  confidence: number;            // confidence score between 0.0 and 1.0
}